name: Update Nix Flake

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}    - uses: cachix/cachix-action@v16
    - uses: cachix/cachix-action@v16
      with:
        name: yuanwang-wf
        signingKey: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Update flake.lock
      uses: DeterminateSystems/update-flake-lock@v28
      with:
        pr-title: "Update flake.lock" # Title of PR to be created
        pr-labels: |
          automated
